services:
  app:
    build: .
    ports:
      - "8080:8501"  # host:container
    volumes:
      - .:/app  # em desenvolvimento, isso permite hot reload (atualização do código sem precisar derrubar o container) --> para produção, remover volume
  
  postgres:
    image: postgres:18.4
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql  # nome do volume --> mapeia --> caminho onde os dados são armazenados no container do PotgreSQL

  pgadmin:
    image: dpage/pgadmin4:9.15
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  postgres_data:
  pgadmin_data: